name: Build App

on:
  #pull_request:
  #push:
  #  branches:
  #    - main
  #    - release
  workflow_dispatch:

env:
  # Our build metadata
  NDK_VERSION: "r26b"

jobs:
  build:
    name: Debug Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.NDK_VERSION }}
          add-to-path: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git openjdk-17-jdk python openjdk-17-jdk-headless
      - name: build
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
        run: |
          export PATH=/usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH
          java -version
          ./gradlew buildNative
          ./gradlew lint assembleDebug

      - uses: actions/upload-artifact@v3
        with:
          name: syncthing-android-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - uses: actions/upload-artifact@v3
        with:
          name: reports-and-libs
          path: |
            app/build/reports/**
            app/src/main/jniLibs/**
