name: Build env test

on:
  #pull_request:
  #push:
  #  branches:
  #    - main
  #    - release
  workflow_dispatch:
jobs:
  build:
    name: Syncthing Build
    runs-on: ubuntu-24.04
    environment: 
      name: AndroidSign
    steps:
      - name: set java home
        run: |
            echo "JAVA_HOME=$JAVA_HOME_21_X64" >> $GITHUB_ENV
            java -version
            echo $JAVA_HOME
            sudo update-alternatives --list java
            sudo update-alternatives --set java $JAVA_HOME
      - name: clean cache
        run: |
            java -version
